{
 "title": "Beekeeper Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "area_name",
    "label": "Area",
    "query": "SELECT name FROM beekeeper.area;"
   },
   {
    "name": "hives",
    "label": "Hives",
    "query": "SELECT id FROM beekeeper.hive WHERE area_name = $area_name;"
   },
   {
    "name": "thc_status",
    "query": "SELECT CONVERT_TZ(NOW(), 'system', 'Europe/Rome') - last_communication as elapsed_time\nFROM beekeeper.node\nWHERE hive_id = ${hives} AND type = 'thc';"
   },
   {
    "name": "fn_status",
    "query": "SELECT CONVERT_TZ(NOW(), 'system', 'Europe/Rome') - last_communication as elapsed_time\nFROM beekeeper.node\nWHERE hive_id = ${hives} AND type = 'fn';"
   },
   {
    "name": "w_status",
    "query": "SELECT CONVERT_TZ(NOW(), 'system', 'Europe/Rome') - last_communication as elapsed_time\nFROM beekeeper.node\nWHERE hive_id = ${hives} AND type = 'w';"
   },
   {
    "name": "c_status",
    "query": "SELECT CONVERT_TZ(NOW(), 'system', 'Europe/Rome') - last_communication as elapsed_time\nFROM beekeeper.node\nWHERE hive_id = ${hives} AND type = 'c';"
   },
   {
    "name": "ta_status",
    "query": "SELECT CONVERT_TZ(NOW(), 'system', 'Europe/Rome') - last_communication as elapsed_time\nFROM beekeeper.node\nWHERE hive_id = ${hives} AND type = 'ta';"
   },
   {
    "name": "va_status",
    "query": "SELECT CONVERT_TZ(NOW(), 'system', 'Europe/Rome') - last_communication as elapsed_time\nFROM beekeeper.node\nWHERE hive_id = ${hives} AND type = 'va';"
   },
   {
    "name": "thc_communication_time",
    "query": "SELECT communication_time\nFROM beekeeper.node\nWHERE hive_id = ${hives} AND type = 'thc';"
   },
   {
    "name": "fn_communication_time",
    "query": "SELECT communication_time\nFROM beekeeper.node\nWHERE hive_id = ${hives} AND type = 'fn';"
   },
   {
    "name": "w_communication_time",
    "query": "SELECT communication_time\nFROM beekeeper.node\nWHERE hive_id = ${hives} AND type = 'w';"
   },
   {
    "name": "c_communication_time",
    "query": "SELECT communication_time\nFROM beekeeper.node\nWHERE hive_id = ${hives} AND type = 'c';"
   },
   {
    "name": "ta_communication_time",
    "query": "SELECT communication_time\nFROM beekeeper.node\nWHERE hive_id = ${hives} AND type = 'ta';"
   },
   {
    "name": "va_communication_time",
    "query": "SELECT communication_time\nFROM beekeeper.node\nWHERE hive_id = ${hives} AND type = 'va';"
   }
  ]
 },
 "panels": [
  { "title": "Hive $hives", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "beekeeper",
     "rawSql": "SELECT convert_tz(m.timestamp,'Europe/Rome','UTC') as time, m.value as temperature\nFROM beekeeper.measurement as m INNER JOIN beekeeper.node as n \nON m.node_id = n.id\nWHERE m.type = 'temperature' AND n.hive_id = ${hives}\nORDER BY timestamp DESC\nLIMIT 50"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "dataset": "beekeeper",
     "rawSql": "SELECT convert_tz(m.timestamp,'Europe/Rome','UTC') as time, m.value as humidity\nFROM beekeeper.measurement as m INNER JOIN beekeeper.node as n \nON m.node_id = n.id\nWHERE m.type = 'humidity' AND n.hive_id = ${hives}\nORDER BY timestamp DESC\nLIMIT 50"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "dataset": "beekeeper",
     "rawSql": "SELECT convert_tz(m.timestamp,'Europe/Rome','UTC') as time, m.value as CO2\nFROM beekeeper.measurement as m INNER JOIN beekeeper.node as n \nON m.node_id = n.id\nWHERE m.type = 'co2' AND n.hive_id = ${hives}\nORDER BY timestamp DESC\nLIMIT 50"
    }
   ]
  },
  {
   "title": "Noise",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "dataset": "beekeeper",
     "rawSql": "SELECT convert_tz(m.timestamp,'Europe/Rome','UTC') as time, m.value as noise\nFROM beekeeper.measurement as m INNER JOIN beekeeper.node as n \nON m.node_id = n.id\nWHERE m.type = 'noise' AND n.hive_id = ${hives}\nORDER BY timestamp DESC\nLIMIT 50"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "dataset": "beekeeper",
     "rawSql": "SELECT convert_tz(m.timestamp,'Europe/Rome','UTC') as time, m.value as frequency\nFROM beekeeper.measurement as m INNER JOIN beekeeper.node as n \nON m.node_id = n.id\nWHERE m.type = 'frequency' AND n.hive_id = ${hives}\nORDER BY timestamp DESC\nLIMIT 50"
    }
   ]
  },
  {
   "title": "Elapsed Time from Last Communication",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "options": {
    "content": "<b>Temperature/Humidity/CO<sub>2</sub> Sensor</b>: <span id='thc' style=\"color:#00ff00\">${thc_status}s</span><br/>\n<b>Frequency/Noise Sensor</b>: <span id='fn' style=\"color:#00ff00\">${fn_status}s</span><br/>\n<b>Weight Sensor</b>: <span id='w' style=\"color:#00ff00\">${w_status}s</span><br/>\n<b>Bees Counter Sensor</b>: <span id='c' id='bcs' style=\"color:#00ff00\">${c_status}s</span><br/>\n<b>Temperature Actuator</b>: <span id='ta' style=\"color:#00ff00\">${ta_status}s</span><br/>\n<b>Ventilation Actuator</b>: <span id='va' style=\"color:#00ff00\">${va_status}s</span><br/>\n\n<script>\n  if(document.getElementById('thc').innerHTML === 's') {\n    document.getElementById('thc').innerHTML = 'None'\n    document.getElementById('thc').style = 'color:#ff0000'\n  }\n  if(document.getElementById('fn').innerHTML === 's') {\n    document.getElementById('fn').innerHTML = 'None'\n    document.getElementById('fn').style = 'color:#ff0000'\n  }\n  if(document.getElementById('c').innerHTML === 's') {\n    document.getElementById('c').innerHTML = 'None'\n    document.getElementById('c').style = 'color:#ff0000'\n  }\n  if(document.getElementById('w').innerHTML === 's') {\n    document.getElementById('w').innerHTML = 'None'\n    document.getElementById('w').style = 'color:#ff0000'\n  }\n  if(document.getElementById('va').innerHTML === 's') {\n    document.getElementById('va').innerHTML = 'None'\n    document.getElementById('va').style = 'color:#ff0000'\n  }\n  if(document.getElementById('ta').innerHTML === 's') {\n    document.getElementById('ta').innerHTML = 'None'\n    document.getElementById('ta').style = 'color:#ff0000'\n  }\n</script>"
   },
   "targets": [
    { "dataset": "beekeeper" }
   ]
  },
  {
   "title": "Node Status",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "options": {
    "content": "<b>Temperature/Humidity/CO<sub>2</sub> Sensor</b>: <span id='thc2' style=\"color:#00ff00\"></span><br/>\n<b>Frequency/Noise Sensor</b>: <span id='fn2' style=\"color:#00ff00\"></span><br/>\n<b>Weight Sensor</b>: <span id='w2' style=\"color:#00ff00\"></span><br/>\n<b>Bees Counter Sensor</b>: <span id='c2' id='bcs' style=\"color:#00ff00\"></span><br/>\n<b>Temperature Actuator</b>: <span id='ta2' style=\"color:#00ff00\"></span><br/>\n<b>Ventilation Actuator</b>: <span id='va2' style=\"color:#00ff00\"></span><br/>\n\n<span id='thc31' style='visibility:hidden'>${thc_status}</span>\n<span id='thc32' style='visibility:hidden'>${thc_communication_time}</span>\n<span id='fn31' style='visibility:hidden'>${fn_status}</span>\n<span id='fn32' style='visibility:hidden'>${fn_communication_time}</span>\n<span id='c31' style='visibility:hidden'>${c_status}</span>\n<span id='c32' style='visibility:hidden'>${c_communication_time}</span>\n<span id='w31' style='visibility:hidden'>${w_status}</span>\n<span id='w32' style='visibility:hidden'>${w_communication_time}</span>\n<span id='ta31' style='visibility:hidden'>${ta_status}</span>\n<span id='ta32' style='visibility:hidden'>${ta_communication_time}</span>\n<span id='va31' style='visibility:hidden'>${va_status}</span>\n<span id='va32' style='visibility:hidden'>${va_communication_time}</span>\n\n<script>\n  var threshold = 3\n\n  var thc_status = parseInt(document.getElementById('thc31').innerHTML)\n  var thc_communication_time = parseInt(document.getElementById('thc32').innerHTML)\n  if (!isNaN(thc_status)) {\n    if (thc_status < thc_communication_time) {\n      document.getElementById('thc2').innerHTML = 'Online'\n    } else if (thc_status > thc_communication_time && thc_status < threshold * thc_communication_time) {\n      document.getElementById('thc2').innerHTML = 'Maybe Offline'\n      document.getElementById('thc2').style = 'color:#ffff00'\n    } else {\n      document.getElementById('thc2').innerHTML = 'Offline'\n      document.getElementById('thc2').style = 'color:#ff0000'\n    } \n  } else {\n    document.getElementById('thc2').innerHTML = 'Not Available'\n    document.getElementById('thc2').style = 'color:#ff0000'\n  }\n\n  var fn_status = parseInt(document.getElementById('fn31').innerHTML)\n  var fn_communication_time = parseInt(document.getElementById('fn32').innerHTML)\n  if (!isNaN(fn_status)) {\n    if (fn_status < fn_communication_time) {\n      document.getElementById('fn2').innerHTML = 'Online'\n    } else if (fn_status > fn_communication_time && fn_status < threshold * fn_communication_time) {\n      document.getElementById('fn2').innerHTML = 'Maybe Offline'\n      document.getElementById('fn2').style = 'color:#ffff00'\n    } else {\n      document.getElementById('fn2').innerHTML = 'Offline'\n      document.getElementById('fn2').style = 'color:#ff0000'\n    }\n  } else {\n    document.getElementById('fn2').innerHTML = 'Not Available'\n    document.getElementById('fn2').style = 'color:#ff0000'\n  }\n\n  var w_status = parseInt(document.getElementById('w31').innerHTML)\n  var w_communication_time = parseInt(document.getElementById('w32').innerHTML)\n  if (!isNaN(w_status)) {\n    if (w_status < w_communication_time) {\n      document.getElementById('w2').innerHTML = 'Online'\n    } else if (w_status > w_communication_time && w_status < threshold * w_communication_time) {\n      document.getElementById('w2').innerHTML = 'Maybe Offline'\n      document.getElementById('w2').style = 'color:#ffff00'\n    } else {\n      document.getElementById('w2').innerHTML = 'Offline'\n      document.getElementById('w2').style = 'color:#ff0000'\n    }\n  } else {\n    document.getElementById('w2').innerHTML = 'Not Available'\n    document.getElementById('w2').style = 'color:#ff0000'\n  }\n\n  var c_status = parseInt(document.getElementById('c31').innerHTML)\n  var c_communication_time = parseInt(document.getElementById('c32').innerHTML)\n  if (!isNaN(c_status)) {\n    if (c_status < c_communication_time) {\n      document.getElementById('c2').innerHTML = 'Online'\n    } else if (c_status > c_communication_time && c_status < threshold * c_communication_time) {\n      document.getElementById('c2').innerHTML = 'Maybe Offline'\n      document.getElementById('c2').style = 'color:#ffff00'\n    } else {\n      document.getElementById('c2').innerHTML = 'Offline'\n      document.getElementById('c2').style = 'color:#ff0000'\n    }\n  } else {\n    document.getElementById('c2').innerHTML = 'Not Available'\n    document.getElementById('c2').style = 'color:#ff0000'\n  }\n\n  var ta_status = parseInt(document.getElementById('ta31').innerHTML)\n  var ta_communication_time = parseInt(document.getElementById('ta32').innerHTML)\n  if (!isNaN(ta_status)) {\n    if (ta_status < ta_communication_time) {\n      document.getElementById('ta2').innerHTML = 'Online'\n    } else if (ta_status > ta_communication_time && ta_status < threshold * ta_communication_time) {\n      document.getElementById('ta2').innerHTML = 'Maybe Offline'\n      document.getElementById('ta2').style = 'color:#ffff00'\n    } else {\n      document.getElementById('ta2').innerHTML = 'Offline'\n      document.getElementById('ta2').style = 'color:#ff0000'\n    }\n  } else {\n    document.getElementById('ta2').innerHTML = 'Not Available'\n    document.getElementById('ta2').style = 'color:#ff0000'\n  }\n\n  var va_status = parseInt(document.getElementById('va31').innerHTML)\n  var va_communication_time = parseInt(document.getElementById('va32').innerHTML)\n  if (!isNaN(va_status)) {\n    if (va_status < va_communication_time) {\n      document.getElementById('va2').innerHTML = 'Online'\n    } else if (va_status > va_communication_time && va_status < threshold * va_communication_time) {\n      document.getElementById('va2').innerHTML = 'Maybe Offline'\n      document.getElementById('va2').style = 'color:#ffff00'\n    } else {\n      document.getElementById('va2').innerHTML = 'Offline'\n      document.getElementById('va2').style = 'color:#ff0000'\n    }\n  } else {\n    document.getElementById('va2').innerHTML = 'Not Available'\n    document.getElementById('va2').style = 'color:#ff0000'\n  }\n\n</script>"
   },
   "targets": [
    { "dataset": "beekeeper" }
   ]
  },
  {
   "title": "Weight",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "beekeeper",
     "rawSql": "SELECT convert_tz(m.timestamp,'Europe/Rome','UTC') as time, m.value as weight\nFROM beekeeper.measurement as m INNER JOIN beekeeper.node as n \nON m.node_id = n.id\nWHERE m.type = 'weight' AND n.hive_id = ${hives}\nORDER BY timestamp DESC\nLIMIT 50"
    }
   ]
  },
  {
   "title": "Bees Counter",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "dataset": "beekeeper",
     "rawSql": "SELECT convert_tz(m.timestamp,'Europe/Rome','UTC') as time, m.value as counter_in, n.value as counter_out\nFROM beekeeper.measurement AS m INNER JOIN beekeeper.measurement AS n ON m.timestamp = n.timestamp INNER JOIN beekeeper.node as o\nON m.node_id = o.id\nWHERE m.type = 'counter_in' AND n.type = 'counter_out' AND o.hive_id = ${hives}\nORDER BY time DESC\nLIMIT 5"
    }
   ]
  }
 ]
}